version: "3"
services:
  app:
    build: .
    restart: always
    expose:
      - 3333
    environment:
      PORT: 3333
      VIRTUAL_HOST: "gittybot.asemanmanzar.ir"
      VIRTUAL_PORT: "3333"
      LETSENCRYPT_HOST: gittybot.asemanmanzar.ir
      LETSENCRYPT_EMAIL: info@gittybot.asemanmanzar.ir
